vich_uploader:
    db_driver: orm
    storage: gaufrette

    metadata:
        type:
            attribute

    mappings:
        bookAds:
            uri_prefix: /bookads
            upload_destination: book_ad_photo
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
