vich_uploader:
    db_driver: orm
    metadata:
        type:
            attribute

    mappings:
        bookAds:
            uri_prefix: /bookads
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
